"""Initial Migration

Revision ID: 2a75013aa9e1
Revises: 
Create Date: 2026-02-23 00:53:32.599547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a75013aa9e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Purchaseorderdetails')
    op.drop_table('Purchaseorder')
    op.create_index(op.f('ix_Category_name'), 'Category', ['name'], unique=True)
    op.create_index(op.f('ix_Customer_name'), 'Customer', ['name'], unique=False)
    op.create_index(op.f('ix_Product_name'), 'Product', ['name'], unique=False)
    op.create_index(op.f('ix_Supplier_name'), 'Supplier', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Supplier_name'), table_name='Supplier')
    op.drop_index(op.f('ix_Product_name'), table_name='Product')
    op.drop_index(op.f('ix_Customer_name'), table_name='Customer')
    op.drop_index(op.f('ix_Category_name'), table_name='Category')
    op.create_table('Purchaseorder',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('purchase_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=18, scale=0), autoincrement=False, nullable=False),
    sa.Column('shipping_cost', sa.DECIMAL(precision=18, scale=0), autoincrement=False, nullable=True),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['Supplier.id'], name=op.f('FK__Purchaseo__suppl__5070F446')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__Purchase__3213E83F98F36B0E'))
    )
    op.create_table('Purchaseorderdetails',
    sa.Column('purchaseorder_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unitcost', sa.DECIMAL(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['Product.id'], name=op.f('FK__Purchaseo__produ__5441852A')),
    sa.ForeignKeyConstraint(['purchaseorder_id'], ['Purchaseorder.id'], name=op.f('FK__Purchaseo__purch__534D60F1')),
    sa.PrimaryKeyConstraint('purchaseorder_id', 'product_id', name=op.f('PK__Purchase__4C809154064B3703'))
    )
    # ### end Alembic commands ###
